blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/rdm9x/pride-team/discussions
    about: Use Discussions for questions, ideas, show-and-tell.
  - name: Security vulnerability
    url: mailto:security@example.com
    about: Please report security issues privately.
